### ISSUE TITLE
Network creation splits arcs at each node

### ISSUE THREAD

**Issue by anitagraser** [pysal/spaghetti#532] opened 2020-10-09 09:18 UTC
After wondering why the number of rows in the streets GeoDataFrame is different from the number of rows in the spaghetti network arcs, I noticed that the network arcs are split at each node of the input line geometries. Is this on purpose? I find it rather unexpected and it can significantly increase the number of arcs in the network. 

```
>>> shp_path = libpysal.examples.get_path("streets.shp")
>>> gdf = geopandas.read_file(shp_path)
>>> len(gdf)
293
>>> ntw = spaghetti.Network(in_data=shp_path)
>>> en(spaghetti.element_as_gdf(ntw1, arcs=True))
303
```

Visualization with point markers at start and end nodes:

![image](https://user-images.githubusercontent.com/590385/95565263-33401100-0a20-11eb-93b8-45e156863c33.png)

**Comment by jGaboardi** [comment] 2020-10-09 14:57
> Is this on purpose? I find it rather unexpected and it can significantly increase the number of arcs in the network.

Yes, this is on purpose and expected, and yes, it will nearly always increase the number of arcs in the network. In [`Network._extractnetwork()`](https://github.com/pysal/spaghetti/blob/48210dcd9cf8d20acb6ddc29305fb40d6a2c950a/spaghetti/network.py#L454) [each line feature](https://github.com/pysal/spaghetti/blob/48210dcd9cf8d20acb6ddc29305fb40d6a2c950a/spaghetti/network.py#L485) is iterated over and [each (euclidean) vertex](https://github.com/pysal/spaghetti/blob/48210dcd9cf8d20acb6ddc29305fb40d6a2c950a/spaghetti/network.py#L497) within each line feature is iterated over in order to build the network data structure. As I mentioned above, this is expected behavior, but I have also realized it is only clarified in the code/comments itself and not in the docstrings/API docs, which should be remedied.

Moreover, like #530, this procedure is a legacy of the implementation in the code design of [`pysal.network`](https://github.com/pysal/pysal/tree/v1.14.4/pysal/network) (see also the migration explanation [here](https://github.com/pysal/pysal/blob/master/MIGRATING.md#porting-your-code)), the predecessor of `pysal/spaghetti`. PySAL itself came into being prior to the advent of the `anaconda`/`conda` ecosystem and until several years ago was nearly 100% non-reliant on outside spatial packages (`shapely`, `geopandas`, etc.) due to the complexity, and frequent breakages, of installing dependencies. When I took over as the lead dev for `spaghetti` I wanted to incorporate functionality from other spatial packages as optional, but also retain the character of the original code base (i.e. utilizing [native PySAL geometries and operations](https://pysal.org/libpysal/api.html#cg-computational-geometry) where possible).

Over the last several years I have gone back and forth on whether to (1) rely on on PySAL where possible; (2) completely restructure the code base to rely on outside packages; or (3) implement a dual workflow whereby users can either use only native PySAL geometries and operations *or* take advantage of outside packages. Each choice does, of course, come with its own set of pros & cons. Many of these thoughts & ideas can be found in the following issues: #403, #373 , #195.

**Comment by anitagraser** [comment] 2020-10-10 07:16
Thank you for the detailed explanations! The joy of legacy systems 😄 

So the legacy behavior is to split the original linestrings at each vertex and - if I interpret `_extractnetwork` correctly - it is not designed to store a linestring / [libpysal.cg.Chain](https://pysal.org/libpysal/generated/libpysal.cg.Chain.html#libpysal.cg.Chain) with the arcs:

https://github.com/pysal/spaghetti/blob/48210dcd9cf8d20acb6ddc29305fb40d6a2c950a/spaghetti/network.py#L531-L535

However, later, functions such as `_snap_to_link` do create chains: 

https://github.com/pysal/spaghetti/blob/48210dcd9cf8d20acb6ddc29305fb40d6a2c950a/spaghetti/network.py#L1203-L1211

I understand the reluctance to restructure everything and rely on outside packages. Luckily in this case, it seems like that's not necessary because PySAL may already include what we need.

**Comment by jGaboardi** [comment] 2020-10-10 12:46
Yeah, before the `v2.0` release (whenever that will be) I would like to work out all the oddities and rough edges like these. For now I am going to close this issue and we can reopen if needed once I have the time to focus back on it. In the meantime, I hope to give #526 some attention this weekend.

**Closed by jGaboardi** 2020-10-10 12:46 UTC
Labels: network instantiation, question
