### ISSUE TITLE
TypeError: '>' not supported between instances of '_NodeCursor' and '_NodeCursor'

### ISSUE THREAD

**Issue by robsalasco** [pysal/spaghetti#196] opened 2018-12-05 16:18 UTC
Hi! @jGaboardi!!

I'm trying to snap points to lines using the function ```net.snapobservations(shp, 'obs')``` with the git version of spaghetti but I have this error. Can you help me please?

Thank you!

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-964ead266930> in <module>
----> 1 net.snapobservations(shp, 'obs', attribute=False)

~/.pyenv/versions/3.6.4/envs/points/lib/python3.6/site-packages/spaghetti/network.py in snapobservations(self, in_data, name, idvariable, attribute)
    773                                                 idvariable=idvariable,
    774                                                 attribute=attribute)
--> 775         self._snap_to_link(self.pointpatterns[name])
    776 
    777 

~/.pyenv/versions/3.6.4/envs/points/lib/python3.6/site-packages/spaghetti/network.py in _snap_to_link(self, pointpattern)
    882             points[point_idx] = point['coordinates']
    883 
--> 884         snapped = util.snap_points_to_links(points, arcs_)
    885 
    886         # record obs_to_arc, dist_to_vertex, and dist_snapped

~/.pyenv/versions/3.6.4/envs/points/lib/python3.6/site-packages/spaghetti/util.py in snap_points_to_links(points, links)
    393 
    394         r = cg.Rect(x0, y0, x1, y1)
--> 395         rt.insert(link, r)
    396 
    397     # Build a KDtree on link vertices.

~/.pyenv/versions/3.6.4/envs/points/lib/python3.6/site-packages/libpysal/cg/rtree.py in insert(self, o, orect)
    198 
    199     def insert(self, o, orect):
--> 200         self.cursor.insert(o, orect)
    201         assert(self.cursor.index == 0)
    202 

~/.pyenv/versions/3.6.4/envs/points/lib/python3.6/site-packages/libpysal/cg/rtree.py in insert(self, leafo, leafrect)
    415                     self.root, leafo, leafrect))
    416 
--> 417                 self._balance()
    418 
    419                 # done: become the original again

~/.pyenv/versions/3.6.4/envs/points/lib/python3.6/site-packages/libpysal/cg/rtree.py in _balance(self)
    460             self.root, k, s_children) for k in range(2, MAX_KMEANS)]
    461         score, bestcluster = max(
--> 462             [(silhouette_coeff(c, memo), c) for c in clusterings])
    463 
    464         nodes = [_NodeCursor.create_with_children(

TypeError: '>' not supported between instances of '_NodeCursor' and '_NodeCursor'
```

**Comment by jGaboardi** [comment] 2018-12-05 16:36
@robsalasco Thanks for the report.

* Did you use `pysal` example data or your own data? If you used your own data, can you post it here in zipped format?
* I have found two similar issues with `libpysal.cg.tree` (see pysal/libpysal#126), but have had no time to dig into the reason of the problems. However, it does at least appear to be an issue with [`libpysal`](https://github.com/pysal/libpysal), and not directly caused by `spaghetti` (though I may be wrong).

**Comment by robsalasco** [comment] 2018-12-05 16:43
Thank you @jGaboardi I'm using my own data... days ago the snapping was ok but now it's broken.

[linesandpoints.zip](https://github.com/pysal/spaghetti/files/2649686/linesandpoints.zip)

**Comment by robsalasco** [comment] 2018-12-05 17:01
hey @jGaboardi I tried installing the development version of libpysal and now it works

**Comment by jGaboardi** [comment] 2018-12-05 17:05
@robsalasco do you know which version of `libpysal` you were using before?

**Comment by robsalasco** [comment] 2018-12-05 17:08
> @robsalasco do you know which version of `libpysal` you were using before?

I was using the version 4.0.1

**Comment by robsalasco** [comment] 2018-12-05 17:09
> @robsalasco do you know which version of `libpysal` you were using before?

I was using the 4.0.1 version

**Comment by jGaboardi** [comment] 2018-12-05 17:54
> ... net.snapobservations(shp, 'obs') with the ***git version*** of spaghetti ...

Which version of spaghetti were you using previously?

**Comment by robsalasco** [comment] 2018-12-05 18:11
I retrieved the version seven days ago unfortunately I don't know exactly what commit

**Comment by jGaboardi** [comment] 2018-12-05 19:53
@robsalasco I was able to recreate your `TypeError` with older versions of both `spaghetti` and `libpysal`, so this not a new bug and seems to have been around for awhile. It appears to have to do with specific geometries in your dataset, though I am not sure what at the moment. I made a notebook and tried to `gist it`, but the renderer seems to be down at the moment so I will just post it in here for now.

[issue_TypeError_from_rtree.ipynb.zip](https://github.com/pysal/spaghetti/files/2650366/issue_TypeError_from_rtree.ipynb.zip)

package versions:
[spaghetti v1.0.2](https://github.com/pysal/spaghetti/releases/tag/v1.0.2)
[libpysal v4.0.0.rc1](https://pypi.org/project/libpysal/4.0.0rc1/)

**Comment by jGaboardi** [comment] 2018-12-05 19:55
If you can track down the specific points/lines that are creating the problem, then we can open a new ticket in `libpysal`.

**Comment by robsalasco** [comment] 2018-12-05 21:19
@jGaboardi thank you for your efforts! I was able to fix the problem with another library hope you can have a look on it to have an idea of what's going on.

https://github.com/brendan-ward/nhdnet/blob/master/nhdnet/geometry/lines.py

usage example

https://github.com/brendan-ward/nhdnet/blob/master/custom/sarp/snap_dams.py

Best, roberto

**Comment by jGaboardi** [comment] 2018-12-05 22:37
I'll let you know when we have a solution.

**Comment by jGaboardi** [comment] 2018-12-06 16:13
[gist of issue_TypeError_from_rtree.ipynb](https://gist.github.com/jGaboardi/cfb52f116b747e652c147629b0f42f48)

**Comment by jGaboardi** [comment] 2019-04-30 15:02
Potential for solution in #259

**Comment by jGaboardi** [comment] 2019-05-11 21:58
@robsalasco  This issue (from the standpoint of `spaghetti`) will be resolved in the master branch of  of `spaghetti` once pysal/spaghetti#259 gets merged.

**Closed** 2019-05-13 23:58 UTC
Labels: bug

**Comment by robsalasco** [comment] 2019-05-14 20:47
omg @jGaboardi congrats!!! I'll try it :)

**Comment by jGaboardi** [comment] 2019-05-14 21:56
The real thanks is for @ljwolf!
